modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="mha"
displayName="mha"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
description='''
Quirks from MHA
'''

[[dependencies.mha]]
modId = "palladium"
mandatory = true
versionRange = ""
ordering = "NONE"
side = "BOTH"
